### ISSUE TITLE
encryption support?

### ISSUE THREAD

**Issue by robjtede** [redox-os/tfs#44]
One of the things missing from the ZFS linux releases right now is encryption support.

The FAQ mentions SPECK and AES but I assume that is for checksums.

If so, Is that something planned for later versions of TFS or would the modular nature of the project make it easy to implement.

**Comment by ticki** [comment]
> The FAQ mentions SPECK and AES but I assume that is for checksums.

Those are ciphers not hash functiosn ☺

**Comment by burdges** [comment]
Are there any current file systems that provide an encrypted "write only" mode using public key cryptography?  I know this proved tricky for systems like Tahoe-LAFS.

**Comment by ticki** [comment]
@burdges I don't think so. In fact, it might not be possible as sufficient disk access would mean that you could rewrite anything you wanted.

**Comment by burdges** [comment]
I haven't thought about it, but yes it'd necessarily leak some file system metadata to avoid over writing anything.  There are stenographic filesystems that avoid this, but they hide only a small amount of data in a large filesystem and protect it using erasure coding, so that's kinda another situation. 

I was thinking more about the problem if receiving email on a home machine or the digital camera problem for journalists where your want to record data, and maybe read it during that session, but you want to forget the key soonish and only be able to access it later.  This could also be done with a hash iteration ratchet, not just public key crypo.  

In fact, these use cases are probably best served by an application that writes the data into encrypted files on an ordinary filesystem, and corrupts their metadata like date, etc., not the file system itself.
